name: odyssey
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  bloc: ^8.1.4
  meta: ^1.15.0
  flutter_bloc: ^8.1.6
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  email_validator: ^3.0.0
  intl_phone_number_input: ^0.7.4
  flutter_launcher_icons: ^0.14.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  share_plus: ^10.1.2
  speech_to_text: ^6.1.1
  flutter_polyline_points: ^2.1.0
  http: ^1.2.2
  flutter_rating: ^2.0.2
  permission_handler: ^11.3.1
  location_web: ^5.0.4
  location_platform_interface: ^5.0.0
  location: ^7.0.1
  flutter_shimmer: ^2.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  flutter_email_sender: ^6.0.3
  firebase_storage: ^12.3.6
  badges: ^3.1.2
  cloud_functions: ^5.1.5
  firebase_app_check: ^0.3.1+6
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  carousel_slider: ^5.0.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  tuple: ^2.0.2
  smooth_page_indicator: ^1.2.0+3
  geolocator: ^13.0.2
  app_settings: ^5.1.1
  flutter_contacts: ^1.1.9
  geocoding : ^3.0.0
  flutter_typeahead: ^5.2.0
  avatar_glow: ^3.0.1
  clipboard: ^0.1.3
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  flutter_cache_manager: ^3.4.1

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/background.png
  - assets/icons/app_icon.png
  - assets/icons8-bell-96.png
  - assets/icons8-add-user-male-96.png
  - assets/circle-profile-pic.jpg
  - assets/photo-1528543606781-2f6e6857f318.jpeg
  - assets/icons8-friends-100.png
  - assets/icons8-passport-100.png
  - assets/location/DLBlissStatePark.jpg
  - assets/location/DLBlissStatePark2.jpg
  - assets/location/DLBlissStatePark3.jpg
  - assets/location/EmeraldBayStatePark.jpg
  - assets/location/EmeraldBayStatePark2.jpg
  - assets/location/EmeraldBayStatePark3.jpg
  - assets/location/HeavenlyMountainResort.jpg
  - assets/location/HeavenlyMountainResort2.jpg
  - assets/location/HeavenlyMountainResort3.jpg
  - assets/location/SandHarbor.jpg
  - assets/location/SandHarbor2.jpg
  - assets/location/SandHarbor3.jpg
  - assets/location/TaylorCreekVisitorsCenter.jpg
  - assets/location/TaylorCreekVisitorsCenter2.jpg
  - assets/location/TaylorCreekVisitorsCenter3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
