// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0qYhEoU3PuAZkFuL6cG2MWDu8J9dxFvE',
    appId: '1:749175602340:web:074ac9bce4c0f6aa377a31',
    messagingSenderId: '749175602340',
    projectId: 'csen268-f24-g7-dcfb7',
    authDomain: 'csen268-f24-g7-dcfb7.firebaseapp.com',
    storageBucket: 'csen268-f24-g7-dcfb7.firebasestorage.app',
    measurementId: 'G-T8L4Z093QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODiKMeJha5QDPmxlL77CauNvVrUNOSgE',
    appId: '1:749175602340:android:a646ae0a75cf99da377a31',
    messagingSenderId: '749175602340',
    projectId: 'csen268-f24-g7-dcfb7',
    storageBucket: 'csen268-f24-g7-dcfb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbBD_DfJBHRpnH6O4Mr9ue4jNCcoHtGQ',
    appId: '1:749175602340:ios:0fd390deac69b571377a31',
    messagingSenderId: '749175602340',
    projectId: 'csen268-f24-g7-dcfb7',
    storageBucket: 'csen268-f24-g7-dcfb7.firebasestorage.app',
    iosBundleId: 'com.example.odyssey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLbBD_DfJBHRpnH6O4Mr9ue4jNCcoHtGQ',
    appId: '1:749175602340:ios:0fd390deac69b571377a31',
    messagingSenderId: '749175602340',
    projectId: 'csen268-f24-g7-dcfb7',
    storageBucket: 'csen268-f24-g7-dcfb7.firebasestorage.app',
    iosBundleId: 'com.example.odyssey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0qYhEoU3PuAZkFuL6cG2MWDu8J9dxFvE',
    appId: '1:749175602340:web:9e717f3fcf20a41d377a31',
    messagingSenderId: '749175602340',
    projectId: 'csen268-f24-g7-dcfb7',
    authDomain: 'csen268-f24-g7-dcfb7.firebaseapp.com',
    storageBucket: 'csen268-f24-g7-dcfb7.firebasestorage.app',
    measurementId: 'G-RFP3CYYFRY',
  );

}